### ISSUE TITLE
The library does not work properly in a monorepo configuration

### ISSUE THREAD

**Issue by chetzof** [antfu/vueuse#259]
When using it in yarn workspaces / lerna environment, the library throws an error with the following structure
- testproject
- - node_modules
- - - @vueuse
- - - vue-demi
- - packages
- - - my-module
- - -  - node_modules
- - - - index.ts with import vueuse from '@vueuse/core'

```
WARNING  Compiled with 1 warnings                                                                                                                                                                    7:45:35 PM

 warning  in /Users/chetzof/Work/testproject/node_modules/@vueuse/core/dist/index.esm.js

"export 'createApp' was not found in 'vue-demi'

ModuleDependencyWarning: "export 'createApp' was not found in 'vue-demi'
    at Compilation.reportDependencyErrorsAndWarnings (/Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1459:23)
    at /Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chetzof/Work/testproject/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chetzof/Work/testproject/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/chetzof/Work/testproject/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/Users/chetzof/Work/testproject/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1185:12
    at /Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
    at HarmonyImportSpecifierDependency._getErrors (/Users/chetzof/Work/testproject/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/chetzof/Work/testproject/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:60:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1454:24)
    at /Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chetzof/Work/testproject/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chetzof/Work/testproject/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/chetzof/Work/testproject/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/Users/chetzof/Work/testproject/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1185:12
    at /Users/chetzof/Work/testproject/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

after i copy `testproject/node_modules/@vueuse` to `testproject/packages/my-module/node_modules` the error goes away

**Comment by antfu** [comment]
Can you share a minimal repro? Thanks.

**Comment by antfu** [comment]
Close for inactive
